# -*- coding: utf-8 -*-
"""machine_learning_hw2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wdb5k_ioL96OFwc8BQYZkZ7tWq2Nn6Ci

# **機器學習 作業二-鐵達尼號 (11/28截止)**

* Due before class meeting on 11/28

---

1. 在 kaggle.com 上預測鐵達尼號生存或死亡人員,  限用上課所提之演算法或 ensemble learning, 可以加上資料處理技巧。

2. 此作業將依準確率打分數, 最高的準確率可得90分, 次高的準確率得89(  or 88分), 依此列推. 若你的準確率沒有與別組相同, 可得額外10分。

3. 請附kaggle準確率截圖, 並顯示出在你前後2筆之排名資料,  python codes 以.py file 上傳。

4. 最多2人一組. 每組只需上傳一份作業。

---

* 競賽網站 : https://www.kaggle.com/competitions/titanic/overview
"""



"""## 手動上傳資料集"""

from google.colab import files
uploaded = files.upload()

"""## 模型本體"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from google.colab import files

uploaded = files.upload()

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")


# =======================================================
# Feature Engineering
# =======================================================
def feature_engineering(df):
    df = df.copy()

    df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
    df["Age"] = df["Age"].fillna(df["Age"].median())
    df["Fare"] = df["Fare"].fillna(df["Fare"].median())

    df["Title"] = df["Name"].apply(lambda x: x.split(",")[1].split(".")[0].strip())
    title_map = {"Mr": "Mr", "Miss": "Miss", "Mrs": "Mrs", "Master": "Master"}
    df["Title"] = df["Title"].map(lambda x: title_map[x] if x in title_map else "Rare")
    df["Title"] = LabelEncoder().fit_transform(df["Title"])

    df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
    df["Embarked"] = LabelEncoder().fit_transform(df["Embarked"])

    df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

    df["TicketGroup"] = df.groupby("Ticket")["Ticket"].transform("count")

    df["Deck"] = df["Cabin"].fillna("Unknown").str[0]
    df["Deck"] = LabelEncoder().fit_transform(df["Deck"])

    df["FarePerPerson"] = df["Fare"] / df["FamilySize"]
    df["AgeClass"] = df["Age"] * df["Pclass"]

    return df


train = feature_engineering(train)
test = feature_engineering(test)


# =======================================================
# 選擇特徵
# =======================================================
features = [
    "Pclass", "Sex", "Age", "Fare",
    "FamilySize", "Title", "Embarked"
]

X_train = train[features]
y_train = train["Survived"]
X_test = test[features]


# =======================================================
# Simple but Powerful Ensemble
# =======================================================
model_lr = LogisticRegression(max_iter=300)
model_rf = RandomForestClassifier(
    n_estimators=400, max_depth=6, random_state=42
)
model_gb = GradientBoostingClassifier()

ensemble = VotingClassifier(
    estimators=[
        ("lr", model_lr),
        ("rf", model_rf),
        ("gb", model_gb)
    ],
    voting="soft"
)

ensemble.fit(X_train, y_train)


# =======================================================
# Prediction + Submission
# =======================================================
pred = ensemble.predict(X_test)

submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": pred
})

submission.to_csv("submission.csv", index=False)
print("submission.csv 已產生")

files.download("submission.csv")