import numpy as np

def simulated_annealing(loss_fn, start_points, field_size, steps=300):
    starts = np.array(start_points, dtype=float).copy()
    paths = []

    for start in starts:
        x, y = start
        current_gpa = loss_fn(x, y)
        best_x, best_y, best_gpa = x, y, current_gpa
        temp_start = 2.0
        path = [(x, y, current_gpa, best_x, best_y, best_gpa, temp_start)]
        temp_decay = 0.8
        step_size = 0.2
        temp = temp_start
        for _ in range(steps):
            # --- Homework algo2: Implement Simulated Annealing ------
            # Steps:
            # 1. Choose a neighbor: dx, dy ? { -step_size, 0, +step_size }
            # 2. Compute the new candidate (nx, ny) and evaluate loss_fn (next_gpa)
            # 3. Compute delta = next_gpa - current_gpa
            # 4. Accept the move if:
            #       �V delta > 0   (improves solution), OR
            #       �V with probability exp(delta / temp)   (explores worse solutions)
            # 5. Update best state if current_gpa is better than best_gpa
            # 6. Decay the temperature (temp *= decay_rate)
            # ---------------------------------------------------------

            # --- IMPLEMENTATION START ---
            pass
            
            # step1.
            dx = np.random.choice([-step_size, 0, step_size])
            dy = np.random.choice([-step_size, 0, step_size])

            while ((dx == 0) and (dy == 0)):
                dx = np.random.choice([-step_size, 0, step_size])
                dy = np.random.choice([-step_size, 0, step_size])

            # step2.
            nx = x + dx
            ny = y + dy
            next_gpa = loss_fn(nx, ny)

            # step3.
            delta = next_gpa - current_gpa

            # step4.
            if ((delta > 0) or (np.exp(delta/temp))):
                x, y, current_gpa = nx, ny, next_gpa

            # step5.
            if (current_gpa > next_gpa):
                best_x, best_y, best_gpa = x, y, current_gpa

            # step6.
            temp *= temp_decay

            # --- IMPLEMENTATION END ---

            # ------------------------------------------------
            # "path" means the whole trajectory of one ship from start to end.
            # Each entry in path should include:
            #   - current ship (x, y, gpa, temp)
            #   - best (x, y, gpa) found so far by this ship
            #
            # You can check example_1.txt (generated by main.py) to verify if your code
            #   produces a similar format and result.
            # You can also refer to algo_example.py for a better understanding.
            # Note: best_gpa should only increase over time.
            # ------------------------------------------------
            if current_gpa > best_gpa:
                best_x, best_y, best_gpa = x, y, current_gpa
            path.append((x, y, current_gpa, best_x, best_y, best_gpa, temp))
        paths.append(path)
    return paths