import numpy as np

def ultimate_algorithm(loss_fn, start_points, field_size, steps=300):
    ships = np.array(start_points, dtype=float).copy()
    n_ships = len(ships)
    paths = [[] for _ in range(n_ships)]
    best_states = []

    for i, (x, y) in enumerate(ships):
        gpa = loss_fn(x, y)
        best_states.append([x, y, gpa])
        paths[i].append((x, y, gpa, x, y, gpa))

    # --- Homework: Implement the Ultimate Algorithm ---
    # You may either:
    #
    # a. Choose an existing method (e.g., Local Beam Search, Genetic Algorithm, etc.)
    #     Example: Local Beam Search
    #     Steps if you choose Local Beam Search:
    #       1. For each current state, generate all 8 neighbors
    #          (using step_size in x and/or y)
    #       2. Collect all neighbors from all k beams
    #       3. Evaluate each neighbor with loss_fn (GPA)
    #       4. Select the top-k neighbors (highest GPA values)
    #       5. These become the new states for the next iteration
    #
    # b. Modify Hill Climbing or Simulated Annealing into an improved version
    #
    # c. Design your own original algorithm
    #
    # ------------------------------------------------------
    
    # --- IMPLEMENTATION START ---
    # Genetic Algorithm

    for _ in range(steps):
        # step1.calculate fitness (use evaluate loss_fn(x, y))
        fitness = np.array([loss_fn(x, y) for x, y in ships])

        # step2.selection
        index = np.argsort(fitness)[::-1]
        half = ships[index[:n_ships//2]]

        # step3.(x, y) crossover
        for i in range(n_ships):
            children = []

            for _ in range(n_ships - len(half)):
                parents = half[np.random.choice(len(half), 2, replace=False)]
                alpha = np.random.rand()
                child = alpha * parents[0] + (1 - alpha) * parents[1]
                children.append(child)

            children = np.array(children)

        # step4.mutation
        mutation = (np.random.rand(*children.shape) - 0.5) * 0.2
        children += mutation

        ships = np.vstack((half, children))

        # --- IMPLEMENTATION END ---

        # ------------------------------------------------
        # "paths" means the collection of all ships' trajectories.
        # For this homework, it should contain 10 paths (one per ship).
        # Each entry in path should include:
        #   - current ship (x, y, gpa)
        #   - best (x, y, gpa) found so far by this ship
        #
        # You can check example_10.txt (generated by main.py) to verify if your code
        #   produces a similar format and result.
        # You can also refer to algo_example.py for a better understanding.
        # Note: best_gpa should only increase over time.
        # ------------------------------------------------
        x, y = ships[i]
        gpa = loss_fn(x, y) 
        best_x, best_y, best_gpa = best_states[i]
        if gpa > best_gpa:
            best_x, best_y, best_gpa = x, y, gpa
            best_states[i] = [best_x, best_y, best_gpa]
        paths[i].append((x, y, gpa, best_x, best_y, best_gpa))
    return paths
