# -*- coding: utf-8 -*-
"""machine_learning_hw1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXLjhVYxp7m6fubQ54yGcn0s0AylV2OQ

# **機器學習 作業一（11/14 截止）**

* Due: before class meeting on 11/14
* weight: 50%

**Applying Pandas and matplotlib to visualize the data set of 113Taipei Traffic A1 $ A2 accident report.**


1. 最高分100 , 次高分:98(暫定) 分數依序排下去.
2. 最多4人一組,
3. 每組只需上傳一份power point, word, or pdf書面報告檔 和 .py file
4. 記得在報告寫上組員學號.

讀取資料（CSV）
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("https://data.taipei/api/frontstage/tpeod/dataset/resource.download?rid=1a08afea-6b2e-4c07-a7a2-17dfba7541f5", encoding="big5", low_memory=False)
plt.rcParams['font.family'] = 'Microsoft JhengHei'

# 顯示前 5 筆資料
df.head()

# 查看欄位
print("欄位數：", len(df.columns))
print(df.columns)

# 資料筆數
print("資料筆數：", len(df))

# 檢查缺失值
df.isna().sum()

"""欄位代碼轉換 - 對照表"""

# =========================
# 所有代碼 → 中文名稱對照表
# =========================

weather_map = {
    1:"暴雨", 2:"強風", 3:"風沙", 4:"霧或煙", 5:"雪",
    6:"雨", 7:"陰", 8:"晴", 9:"風"
}

light_map = {
    1:"日間自然光線", 2:"晨或暮光",
    3:"夜間有照明(隧道/地下/涵洞)",
    4:"夜間無照明(隧道/地下/涵洞)",
    5:"有照明且開啟",
    6:"有照明未開啟或障礙",
    7:"無照明"
}

road_type_map = {
    1:"國道", 2:"省道", 3:"縣道", 4:"鄉道", 5:"市區道路",
    6:"村里道路", 7:"專用道路", 8:"其他", 9:"快速道路"
}

road_shape_map = {
    1:"平交道-有遮斷器",
    2:"平交道-無遮斷器",
    3:"三岔路",
    4:"四岔路",
    5:"多岔路",
    6:"隧道",
    7:"地下道",
    8:"橋樑",
    9:"涵洞",
    10:"高架道路",
    11:"彎曲道路",
    12:"坡路",
    13:"巷弄",
    14:"直路",
    18:"圓環",
    19:"廣場",
    20:"休息站或服務區",
    21:"輕軌共用道路",
    22:"其他"
}

accident_location_map = {
    1:"交岔路口內",
    2:"交岔口附近",
    3:"機慢車待轉區",
    4:"機慢車停等區",
    5:"交通島",
    6:"迴轉道",
    7:"快車道",
    8:"慢車道",
    9:"一般車道",
    10:"公車專用道",
    11:"機車專用道",
    12:"機車優先道",
    13:"路肩/路緣",
    14:"加速車道",
    15:"減速車道",
    16:"直線匝道",
    17:"環道匝道",
    18:"行人穿越道",
    19:"行人穿越道附近",
    20:"人行道",
    22:"其他",
    23:"自行車專用道",
    24:"人行道標線",
    25:"騎樓"
}

pavement_type_map = {
    1:"柏油", 2:"水泥", 3:"碎石", 4:"其他鋪裝", 5:"無鋪裝"
}

pavement_status_map = {
    1:"冰雪", 2:"油滑", 3:"泥濘", 4:"濕潤", 5:"乾燥"
}

pavement_defect_map = {
    1:"路面鬆軟", 3:"有坑洞", 5:"隆起/凹陷不平", 4:"無缺陷"
}

road_obstacle_map = {
    1:"道路施工中", 2:"堆積物", 3:"停車阻礙", 6:"攤位棚架",
    4:"其他障礙物", 5:"無障礙物"
}

sight_map = {
    8:"建築物遮蔽", 9:"樹木或農作物遮蔽", 10:"停放車輛遮蔽",
    11:"施工圍籬遮蔽", 12:"其他遮蔽物",
    13:"視距良好",   # 無遮蔽物
    1:"彎道視距不良", 2:"坡道視距不良", 3:"建物視距不良",
    4:"樹木視距不良", 5:"停車視距不良", 6:"其他視距不良",
    7:"視距良好"
}

signal_type_map = {
    1:"行車管制號誌",
    2:"行車管制號誌(含行人號誌)",
    3:"閃光號誌",
    4:"無號誌"
}

signal_status_map = {
    1:"正常",
    2:"不正常",
    3:"無動作",
    4:"無號誌"
}

divider_map = {
    1:"中央分向島-寬式",
    2:"中央分向島-窄式附欄杆",
    3:"中央分向島-窄式無欄杆",
    4:"雙向禁止超車線-附標記",
    5:"雙向禁止超車線-無標記",
    6:"單向禁止超車線-附標記",
    7:"單向禁止超車線-無標記",
    8:"行車分向線-附標記",
    9:"行車分向線-無標記",
    10:"無分向設施"
}

lanes_division_map = {
    1:"禁止變換車道線(附標記)",
    2:"禁止變換車道線(無標記)",
    3:"車道線(附標記)",
    4:"車道線(無標記)",
    5:"未劃設車道線"
}

fastslow_division_map = {
    1:"寬式快慢車道分隔島",
    2:"窄式快慢車道分隔島(附欄杆)",
    3:"窄式快慢車道分隔島(無欄杆)",
    4:"快慢車道分隔線",
    5:"未劃設快慢車道分隔線"
}

accident_type_map = {
    1:"人車-對向通行中",
    2:"人車-同向通行中",
    3:"人車-穿越道路中",
    4:"人車-嬉戲",
    5:"人車-作業中",
    6:"人車-衝入道路",
    7:"人車-從停車處穿出",
    8:"人車-佇立路邊",
    9:"人車-其他",

    10:"車車-對撞",
    11:"車車-對向擦撞",
    12:"車車-同向擦撞",
    13:"車車-追撞",
    14:"倒車撞",
    15:"路口交岔撞",
    16:"側撞",
    17:"其他車車事故",

    18:"翻覆/摔倒",
    19:"衝出路外",
    20:"撞護欄",
    21:"撞號誌桿",
    22:"撞收費亭",
    23:"撞交通島",
    24:"撞非固定設施",
    25:"撞建築物",
    26:"撞路樹/電桿",
    27:"撞動物",
    28:"撞工程施工",
    29:"其他",
    30:"撞壞遮斷器",
    31:"越過平交道中",
    32:"暫停位置不當",
    33:"平交道內無法行動",
    34:"其他平交道事故",
    35:"撞橋樑",
    36:"撞建築物",
    37:"撞路樹",
    38:"撞電桿"
}

# 車種
vehicle_type_map = {
    "A01":"公營公車","A02":"民營公車","A03":"公營客運","A04":"民營客運",
    "A05":"遊覽車","A06":"自用大客車",
    "A11":"營業用大貨車","A12":"自用大貨車",
    "A21":"營業用全聯結車","A22":"自用全聯結車",
    "A31":"營業用半聯結車","A32":"自用半聯結車",
    "A41":"營業用曳引車","A42":"自用曳引車",

    "B01":"計程車","B02":"租賃車","B03":"自用小客車",
    "B11":"營業用小貨車","B12":"自用小貨車","B13":"租賃小貨車",

    "C01":"大型重型(550cc↑)","C02":"大型重型(250–550cc)",
    "C03":"普通重型","C04":"普通輕型","C05":"小型輕型",

    "D01":"軍車-大客車","D02":"軍車-載重車","D03":"軍車-小型車",

    "E01":"救護車","E02":"消防車","E03":"警備車","E04":"工程車","E05":"其他特種車",

    "F01":"腳踏車","F02":"電動輔助自行車","F03":"微型電動二輪車",
    "F04":"人力車","F05":"獸力車","F06":"其他慢車","F07":"個人行動裝置",

    "G01":"拼裝車","G02":"農耕機","G03":"動力機械","G04":"拖車架",
    "G05":"火車","G06":"其他車","G07":"捷運車輛",

    "H01":"行人","H02":"乘客","H03":"其他人","H04":"代步器材"
}

# 車輛用途
vehicle_usage_map = {
    1:"砂石車", 2:"幼童專用車", 3:"校車", 4:"身障特製車",
    5:"教練車", 6:"危險物車", 7:"其他", 8:"非駕駛及乘客"
}

# 行動狀態
action_status_map = {
    1:"起步", 2:"倒車", 3:"停車操作",
    4:"超車", 5:"左轉", 6:"右轉",
    7:"左變換車道", 8:"右變換車道",
    9:"直行", 10:"插入行列",
    11:"迴轉/橫越", 12:"急減速",
    13:"靜止", 14:"停等", 15:"其他",
    16:"步行", 17:"靜立", 18:"奔跑", 19:"上下車",
    20:"其他", 21:"不明"
}

license_status_map = {
    1:"正常駕照", 2:"無照未達年齡", 3:"無照已達年齡", 4:"越級駕駛",
    5:"吊扣", 6:"吊銷", 7:"不明", 8:"無需駕照"
}

license_type_map = {
    1:"職業-聯結車", 2:"職業-大客車", 3:"職業-大貨車", 4:"職業-小型車",
    5:"普通-聯結車", 6:"普通-大客車", 7:"普通-大貨車", 8:"普通-小型車",
    9:"機車-大型重型", 10:"機車-普通重型", 11:"機車-輕型",
    21:"機車-小型輕型",
    12:"軍用-大客車", 13:"軍用-載重車", 14:"軍用-小型車",
    15:"國際駕照", 16:"其他駕照", 17:"學習駕照",
    18:"無照", 19:"不明", 20:"無需駕照"
}

alcohol_map = {
    1:"未飲酒", 2:"無酒精反應", 3:"低度酒測",
    4:"酒測0.15~0.25", 5:"酒測0.25~0.4",
    6:"酒測0.4~0.55", 7:"酒測0.55~0.8",
    8:"酒測>0.8", 9:"無法檢測",
    10:"非駕駛未檢測", 11:"不明"
}

# 肇因碼 (01~131 全部)
cause_map = {
    1:"違規超車", 2:"搶道行駛", 4:"逆向行駛", 5:"未靠右",
    8:"左轉未依規定", 9:"右轉未依規定",
    10:"迴轉未依規定", 11:"橫越道路不慎",
    13:"超速", 14:"未減速", 16:"未保持安全距離",
    17:"未保持安全間隔", 18:"停車未注意安全",
    19:"起步未注意安全",
    20:"吸毒駕駛", 21:"酒駕", 22:"疲勞駕駛",
    24:"搶越平交道",
    27:"燈光使用不當", 28:"暗處停車無燈",
    29:"夜間無燈",
    30:"裝載不穩妥", 31:"超重", 32:"超載",
    33:"超長/寬/高", 34:"裝卸不當", 35:"裝載未盡安全措施",
    36:"未待乘客上下即開車",
    38:"違規臨停", 39:"拋錨未採安全措施",
    40:"開關車門不當",
    42:"其他不當駕駛",
    44:"無肇因",
    45:"煞車失靈", 46:"方向故障", 47:"燈光故障",
    48:"輪胎爆裂", 49:"零件脫落", 50:"其他機件故障",
    53:"穿越未注意左右車",
    54:"在道路上嬉戲", 55:"未停妥上下車",
    56:"上下車未注意安全",
    57:"頭手伸出車外",
    58:"乘坐不當",
    59:"道路作業未設標識",
    60:"其他行為過失",
    61:"危險路況未設警示",
    62:"交通管制設備失靈",
    64:"平交道守望失誤",
    65:"其他交通管制不當",
    66:"動物竄出",
    67:"無肇因(物/動物)",
    68:"危險駕駛",
    69:"未遵守交通指揮",
    70:"未讓行人",
    71:"號誌路口未禮讓直行車",
    72:"無號誌-支線道未禮讓幹線",
    73:"無號誌-少線未讓多線",
    74:"轉彎車未讓直行車",
    75:"無號誌-左車未讓右車",
    76:"山路未讓外側車",
    77:"坡路未讓上車",
    78:"圓環未禮讓",
    79:"未避讓緊急車輛",
    80:"其他未讓車",
    81:"闖紅燈直行", 82:"闖紅燈右轉", 83:"闖紅燈左轉",
    84:"違反閃光號誌", 85:"違反其他號誌",
    86:"違反方向標誌", 87:"違反專用標誌",
    88:"違反行人專用標誌",
    89:"違反禁止進入", 90:"違反禁止車輛進入",
    91:"違反禁止會車",
    92:"違反禁止迴轉",
    93:"違反改道標誌",
    94:"禁止超車標線",
    95:"禁止變換車道標線",
    96:"違反二段式左/右轉",
    97:"違反禁行車種",
    98:"違反禁止左/右轉標誌",
    99:"違反其他禁令標誌",
    100:"變換車道不當",
    101:"方向不定",
    102:"閃避不當",
    103:"多車道迴轉未先入內側",
    104:"打瞌睡",
    105:"飲食/抽菸/撿物分心",
    106:"乘客干擾分心",
    107:"觀看事故分心",
    108:"恍神/緊張/分心",
    109:"自動駕駛設備使用不當",
    110:"觀看行車/娛樂設備",
    111:"使用手機",
    112:"未保持平交道淨空",
    113:"車輛滑動發生事故",
    114:"事故後未採取安全措施",
    115:"不明物體反彈撞擊",
    116:"機械操作不當",
    117:"光線/視線遮蔽",
    118:"證據不足無法判斷",
    119:"肇逃未查獲無法判斷",
    120:"附屬機具未安全措施",
    121:"未依標線穿越",
    122:"未依號誌穿越",
    123:"未依規定使用天橋/地下道",
    124:"搶越平交道",
    125:"事故後離開現場",
    126:"乘客開關車門不當",
    127:"指揮不當",
    128:"施工防護不當",
    129:"道路設施倒塌",
    130:"物品掉落",
    131:"強風/暴雨/濃霧"
}

# 把 df[x] = 中文字典
def apply_map(df, col, mp):
    if col in df.columns:
        df[col] = df[col].map(mp).fillna(df[col])
        print(f"✔ 已轉換欄位：{col}")

# ====== 開始轉換 ======
apply_map(df, "天候", weather_map)
apply_map(df, "道路照明設備", light_map)
apply_map(df, "道路類別", road_type_map)
apply_map(df, "道路型態", road_shape_map)
apply_map(df, "事故位置", accident_location_map)

apply_map(df, "路面鋪裝", pavement_type_map)
apply_map(df, "路面狀態", pavement_status_map)
apply_map(df, "路面缺陷", pavement_defect_map)
apply_map(df, "道路障礙", road_obstacle_map)
apply_map(df, "視距", sight_map)

apply_map(df, "號誌種類", signal_type_map)
apply_map(df, "號誌動作", signal_status_map)

apply_map(df, "車道劃分_分向", divider_map)
apply_map(df, "車道劃分_車道線", lanes_division_map)
apply_map(df, "車道劃分_快慢車", fastslow_division_map)

apply_map(df, "事故類型", accident_type_map)
apply_map(df, "車輛撞擊部位1", accident_type_map)
apply_map(df, "車輛撞擊部位2", accident_type_map)

apply_map(df, "車種", vehicle_type_map)
apply_map(df, "車輛用途", vehicle_usage_map)
apply_map(df, "當事人行動狀態", action_status_map)

apply_map(df, "駕照狀態", license_status_map)
apply_map(df, "駕照種類", license_type_map)
apply_map(df, "飲酒情形", alcohol_map)

apply_map(df, "肇因碼-個別", cause_map)
apply_map(df, "肇因碼-主要", cause_map)

print("🎉 所有代碼欄位已轉換為中文！")

"""新增欄位與基本前處理"""

# 將「發生年度 / 月 / 日」轉成 datetime
# 注意：需先轉成整數
df['發生年度'] = pd.to_numeric(df['發生年度'], errors='coerce')
df['發生月'] = pd.to_numeric(df['發生月'], errors='coerce')
df['發生日'] = pd.to_numeric(df['發生日'], errors='coerce')

date_df = df[['發生年度', '發生月', '發生日']].rename(
    columns={'發生年度': 'year', '發生月': 'month', '發生日': 'day'}
)

df['發生日期'] = pd.to_datetime(date_df, errors='coerce')

# 建立星期欄位（0=星期一, 6=星期日）
df['星期'] = df['發生日期'].dt.dayofweek

# 將星期編號轉換成中文標籤方便解讀
weekday_map = {0: '一', 1: '二', 2: '三', 3: '四', 4: '五', 5: '六', 6: '日'}
df['星期_中文'] = df['星期'].map(weekday_map)

# 處理「發生時-Hours」欄位
df['發生時-Hours'] = pd.to_numeric(df['發生時-Hours'], errors='coerce')

# 依死亡人數建立 A1 / A2 類別
df['死亡人數'] = pd.to_numeric(df['死亡人數'], errors='coerce').fillna(0)
df['事故類型'] = df['死亡人數'].apply(lambda x: 'A1(死亡事故)' if x > 0 else 'A2(受傷事故)')

df[['發生日期', '星期_中文', '發生時-Hours', '死亡人數', '事故類型']].head()

"""依事故時段分布"""

hour_counts = df['發生時-Hours'].value_counts().sort_index()

plt.figure(figsize=(12, 6))
plt.plot(hour_counts.index, hour_counts.values, marker='o')
plt.xlabel("發生時段（小時）")
plt.ylabel("事故件數")
plt.title("113 年臺北市交通事故 - 依時段分布")
plt.grid(True)
plt.xticks(range(0, 24))
plt.show()

"""天候分布"""

weather_counts = df['天候'].value_counts()

plt.figure(figsize=(10, 6))
plt.bar(weather_counts.index.astype(str), weather_counts.values)
plt.xlabel("天候")
plt.ylabel("事故件數")
plt.title("113 年臺北市交通事故 - 天候分布")
plt.xticks(rotation=45)
plt.show()

vehicle_counts = df['車種'].value_counts().head(15)

plt.figure(figsize=(10, 6))
plt.bar(vehicle_counts.index.astype(str), vehicle_counts.values)
plt.xlabel("車種")
plt.ylabel("事故件數")
plt.title("113 年臺北市交通事故 - 前 15 大車種統計")
plt.xticks(rotation=45)
plt.show()

vehicle_counts

gender_counts = df["性別"].value_counts()

plt.figure(figsize=(6,6))
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%')
plt.title("駕駛者性別分布")
plt.show()

gender_counts

# 先把年齡層轉成數字
df["年齡"] = pd.to_numeric(df["年齡"], errors="coerce")

# 定義區間
bins = [0, 17, 24, 34, 44, 54, 64, 120]
labels = ["0–17歲", "18–24歲", "25–34歲", "35–44歲", "45–54歲", "55–64歲", "65歲以上"]

df["年齡"] = pd.cut(df["年齡"], bins=bins, labels=labels, right=True)

import seaborn as sns

heat2 = pd.crosstab(df["年齡"], df["性別"])

plt.figure(figsize=(8,6))
sns.heatmap(heat2, annot=True, cmap="YlOrRd")
plt.title("性別 × 年齡區間 事故熱圖")
plt.show()

# 取每個行政區的事故數
df["區序"] = df["區序"].str.replace(r"^\d+", "", regex=True)
district_counts = df["區序"].value_counts()

plt.figure(figsize=(12,6))
plt.bar(district_counts.index, district_counts.values)
plt.xlabel("行政區")
plt.ylabel("事故件數")
plt.title("113 年台北市各行政區事故排行榜")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,8))
plt.pie(district_counts.values, labels=district_counts.index, autopct='%1.1f%%')
plt.title("行政區事故比例分布")
plt.show()

district_counts.to_frame(name="事故件數")