# -*- coding: utf-8 -*-
"""test3-decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Im0H6ScR8u6831i93NyyvqE6MKdpBoD3
"""

from sklearn import tree, metrics
import numpy as np

X = np.array([
    [0,0,0,0],
    [0,0,0,1],
    [2,0,0,0],
    [1,1,0,0],
    [1,2,1,0],
    [1,2,1,1],
    [2,2,1,1],
    [0,1,0,0],
    [0,2,1,0],
    [1,1,1,0],
    [0,1,1,1],
    [2,1,0,1],
    [2,0,1,0],
    [1,1,0,1]
])

y = np.array([0,0,1,1,1,0,1,0,1,1,1,1,1,0])

dtc = tree.DecisionTreeClassifier(criterion="entropy", random_state=0)
dtc.fit(X, y)

new_data = np.array([[1, 0, 1, 0]])
prediction = dtc.predict(new_data)

print("Yes") if (prediction[0] == 1) else print("No")