# -*- coding: utf-8 -*-
"""test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jYWMO6y7dv8c8TqKFt8BlFqvVmLu2UA
"""

def read_matrix(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = [line.strip() for line in f.readlines() if line.strip()]
    m = int(lines[0])
    matrix = [list(map(int, line.split(','))) for line in lines[1:1+m]]
    return m, matrix

def calc_cost(matrix, x1, y1, x2, y2):
    m = len(matrix)
    cost = 0
    # 基地內
    for i in range(x1, x2 + 1):
        for j in range(y1, y2 + 1):
            if 0 <= i < m and 0 <= j < m:
                cost += matrix[i][j]
    # 鄰近八格區域
    for i in range(x1 - 1, x2 + 2):
        for j in range(y1 - 1, y2 + 2):
            if 0 <= i < m and 0 <= j < m:
                if not (x1 <= i <= x2 and y1 <= j <= y2):
                    cost += 0.5 * matrix[i][j]
    return cost

def find_best_base(matrix, base_h, base_w):
    m = len(matrix)
    best_cost = float('inf')
    best_pos = None

    for x1 in range(m - base_h + 1):
        for y1 in range(m - base_w + 1):
            x2, y2 = x1 + base_h - 1, y1 + base_w - 1
            cost = calc_cost(matrix, x1, y1, x2, y2)

            if best_pos is None:
                best_cost = cost
                best_pos = (x1, y1, x2, y2)
            else:
                bx1, by1, bx2, by2 = best_pos
                # 依據規則：先最小成本 → 再最底 → 再最右
                if (cost < best_cost or
                    (cost == best_cost and x2 > bx2) or
                    (cost == best_cost and x2 == bx2 and y2 > by2)):
                    best_cost = cost
                    best_pos = (x1, y1, x2, y2)

    return best_pos, best_cost

if __name__ == "__main__":
    file_path = "/content/drive/MyDrive/1.csv"
    m, matrix = read_matrix(file_path)

    # 嘗試兩種基地樣式
    styles = [(2, 3), (3, 2)]
    best_result = None
    best_cost = float('inf')

    for h, w in styles:
        pos, cost = find_best_base(matrix, h, w)
        if (cost < best_cost or
            (cost == best_cost and pos[2] > (best_result[0][2] if best_result else -1)) or
            (cost == best_cost and pos[2] == (best_result[0][2] if best_result else -1) and pos[3] > (best_result[0][3] if best_result else -1))):
            best_result = (pos, cost)
            best_cost = cost

    best_pos = best_result[0]
    print(f"{best_pos[0]} {best_pos[1]}")
    print(f"{best_pos[2]} {best_pos[3]}")