# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nz8YqMXBXGmY5kKi89J4MfN4Yo53BE5H
"""

# magic_triangle.py
# 讀入格式: 在 "Enter 4 values separated by spaces: " 提示下輸入 4 個數字
# 第一個為 N，其餘三個為依序填入位置 2,5,8 的值（從頂點開始順時針算第2,5,8）。
# 範例: 若輸入 "1 4 3 6" -> 輸出 542937168

import sys
from itertools import permutations

def solve(N, a2, a5, a8):
    nums = list(range(N, N+9))  # 9 個連續數字
    fixed = {2: a2, 5: a5, 8: a8}  # 固定位置（1-based）
    # 驗證固定值合法性：必須在範圍內且互不相同
    if any(x not in nums for x in fixed.values()) or len(set(fixed.values())) < 3:
        return 0

    # 可用數字是去掉已固定的
    remaining = [x for x in nums if x not in fixed.values()]

    best = None  # 儲存最小的字串表示（轉成 int 比較也可）
    # 我們的三角形位置以 1..9 表示，輸出格式要從位置1開始順時針列出9個數
    # 已知位置 2,5,8 固定，其餘位置為 1,3,4,6,7,9（任意排列）
    free_positions = [1,3,4,6,7,9]

    for perm in permutations(remaining):
        # 建立位置對應
        pos = {}
        for k,v in fixed.items():
            pos[k] = v
        for p,val in zip(free_positions, perm):
            pos[p] = val

        # 計算三邊的和：邊1 = positions 1,2,3,4; 邊2 = 4,5,6,7; 邊3 = 7,8,9,1
        s1 = pos[1] + pos[2] + pos[3] + pos[4]
        s2 = pos[4] + pos[5] + pos[6] + pos[7]
        s3 = pos[7] + pos[8] + pos[9] + pos[1]

        if s1 == s2 == s3:
            # 形成一個解，組成輸出字串（從1到9）
            out_str = ''.join(str(pos[i]) for i in range(1,10))
            # 選最小（數字大小）
            if best is None or int(out_str) < int(best):
                best = out_str

    return int(best) if best is not None else 0

def main():
    try:
        vals = input("Enter 4 values separated by spaces: ").strip().split()
        if len(vals) != 4:
            print("0")
            return
        N = int(vals[0])
        a2 = int(vals[1])
        a5 = int(vals[2])
        a8 = int(vals[3])
    except:
        print("0")
        return

    print(solve(N, a2, a5, a8))

if __name__ == "__main__":
    main()

