# -*- coding: utf-8 -*-
"""machine_learning_HW3_Tiny_ImageNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntO2heZt5QV85K7YjcPhjIeRj_74gNMc

# **機器學習 作業三-Tiny ImageNet Challenge**

* Due before class meeting on 12/19

---

1. 在kaggle.com 上預測Tiny ImageNet Challenge之testing data,  限用pytorch CNN, 可以加上資料處理技巧
2. 此作業將依準確率打分數, 最高的準確率可得90分, 次高的準確率得89(or 88分), 依此列推. 若你的準確率沒有與別組相同, 可得額外10分
3. 請附kaggle準確率截圖,  python codes 以.py file 上傳
4.  最多2人一組. 每組只需上傳一份作業

---

* 資料網站 :https://www.kaggle.com/competitions/deep-learning-thu-2020/data

### 安裝套件（PyTorch + CNN）
"""

!pip install -q kaggle kagglehub timm

"""### 從 Kaggle 下載訓練資料（需上傳 API Token）




"""

from google.colab import files
files.upload()   # 上傳 kaggle.json

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls -lah ~/.kaggle/kaggle.json

"""### 下載 Tiny ImageNet Dataset"""

import kagglehub

DATASET_SLUG = "mikewallace250/tiny-imagenet-challenge"
path = kagglehub.dataset_download(DATASET_SLUG)
print("Dataset path:", path)

!ls -lah {path}

"""### 參數設定"""

DATA_DIR = path
OUT_DIR  = "./out"

EPOCHS = 80            # 衝分建議 80~120
BATCH_SIZE = 512       # T4 常用 256；L4/A100 可試 512
LR = 2e-3
IMG_SIZE = 64

ARCH = "tf_efficientnet_b0"   # CNN：也可用 "resnet34", "resnet50", "tf_efficientnet_b1"
PRETRAINED = True
TTA = True

SEED = 42
NUM_WORKERS = 8        # T4: 4~6；A100: 8

from pathlib import Path

BASE = Path(path)

# 找到 train.txt 所在的資料夾（支援多層）
candidates = list(BASE.rglob("train.txt"))
print("Found train.txt:", candidates[:5])

if len(candidates) == 0:
    raise FileNotFoundError(f"Cannot find train.txt under: {BASE}")

DATA_DIR = str(candidates[0].parent)   # train.txt 的那一層就是資料根目錄
print("✅ DATA_DIR set to:", DATA_DIR)

!ls -lah "{DATA_DIR}"

"""### Imports + Dataset + Dataloader"""

import os, math, time, random
from pathlib import Path
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import timm

def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True

seed_everything(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

class TrainValDataset(Dataset):
    """
    Supports train.txt/val.txt where image_name might be:
    - "72/72_21.jpg"
    - "train/72/72_21.jpg"
    - "val/72/72_21.jpg"
    - "72_21.jpg" (rare)
    """
    def __init__(self, root, split="train", transform=None):
        self.root = Path(root)
        self.split = split
        self.transform = transform
        self.samples = []

        txt_file = self.root / f"{split}.txt"
        if not txt_file.exists():
            raise FileNotFoundError(f"Missing: {txt_file}")

        split_dir = self.root / split
        if not split_dir.exists():
            raise FileNotFoundError(f"Missing: {split_dir}")

        with open(txt_file, "r") as f:
            for line in f:
                name, label = line.strip().split()
                rel = Path(name)

                # 先嘗試：root/name（如果 txt 已經含 train/val 前綴，這個會對）
                p1 = self.root / rel

                # 再嘗試：root/split/name（如果 txt 沒含 train/val 前綴，這個會對）
                p2 = split_dir / rel

                if p1.exists():
                    img_path = p1
                elif p2.exists():
                    img_path = p2
                else:
                    # 最後保底：只取檔名在 split 內遞迴找（慢，但只在少數壞資料列觸發）
                    matches = list(split_dir.rglob(rel.name))
                    if len(matches) > 0:
                        img_path = matches[0]
                    else:
                        raise FileNotFoundError(f"Image not found for line: {name} (tried {p1} and {p2})")

                self.samples.append((img_path, int(label)))

        print(f"[Dataset] {split}: {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        p, y = self.samples[idx]
        img = Image.open(p).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, y

class TestDataset(Dataset):
    def __init__(self, root, transform=None):
        self.root = Path(root)
        self.transform = transform
        test_dir = self.root / "test"
        if not test_dir.exists():
            raise FileNotFoundError(f"Missing: {test_dir}")

        self.paths = sorted(test_dir.glob("*.jpg"), key=lambda p: int(p.stem))
        print(f"[Dataset] test: {len(self.paths)} images")

    def __len__(self): return len(self.paths)

    def __getitem__(self, idx):
        p = self.paths[idx]
        img = Image.open(p).convert("RGB")
        if self.transform: img = self.transform(img)
        return img, p.name

# ---- Strong augmentation ----
train_tf = T.Compose([
    T.RandomResizedCrop(IMG_SIZE, scale=(0.7, 1.0), ratio=(0.75, 1.33)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandAugment(num_ops=2, magnitude=9),
    T.ColorJitter(0.2,0.2,0.2,0.1),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225)),
    T.RandomErasing(p=0.25, scale=(0.02, 0.2), ratio=(0.3, 3.3), value="random"),
])

test_tf = T.Compose([
    T.Resize(IMG_SIZE),
    T.CenterCrop(IMG_SIZE),
    T.ToTensor(),
    T.Normalize((0.485,0.456,0.406),(0.229,0.224,0.225)),
])

train_ds = TrainValDataset(DATA_DIR, "train", train_tf)
val_ds   = TrainValDataset(DATA_DIR, "val", test_tf)
test_ds  = TestDataset(DATA_DIR, test_tf)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=True, drop_last=True)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)

print("sizes:", len(train_ds), len(val_ds), len(test_ds))

"""### 建立 CNN 模型（timm）"""

model = timm.create_model(
    ARCH,
    pretrained=PRETRAINED,
    num_classes=100
).to(device)

print("Model:", ARCH)

"""### 訓練（MixUp/CutMix + Label smoothing + Cosine warmup + EMA + AMP）"""

class SoftTargetCrossEntropy(nn.Module):
    def __init__(self, label_smoothing=0.1):
        super().__init__()
        self.ls = label_smoothing

    def forward(self, logits, target):
        if target.dim() == 1:
            c = logits.size(1)
            with torch.no_grad():
                t = torch.zeros_like(logits).fill_(self.ls/(c-1))
                t.scatter_(1, target.unsqueeze(1), 1.0 - self.ls)
            target = t
        logp = torch.log_softmax(logits, dim=1)
        return (-target * logp).sum(dim=1).mean()

def mixup_cutmix(x, y, num_classes=100, mixup_alpha=0.2, cutmix_alpha=1.0, p=0.8):
    if random.random() > p:
        return x, y, None

    bs = x.size(0)
    idx = torch.randperm(bs, device=x.device)
    x2, y2 = x[idx], y[idx]

    use_cutmix = random.random() < 0.5
    if use_cutmix:
        lam = np.random.beta(cutmix_alpha, cutmix_alpha)
        W, H = x.size(3), x.size(2)
        cut_rat = np.sqrt(1. - lam)
        cw, ch = int(W * cut_rat), int(H * cut_rat)
        cx, cy = np.random.randint(W), np.random.randint(H)

        x1 = int(np.clip(cx - cw//2, 0, W)); x2b = int(np.clip(cx + cw//2, 0, W))
        y1 = int(np.clip(cy - ch//2, 0, H)); y2b = int(np.clip(cy + ch//2, 0, H))

        x[:, :, y1:y2b, x1:x2b] = x2[:, :, y1:y2b, x1:x2b]
        lam = 1 - ((x2b-x1)*(y2b-y1)/(W*H))
    else:
        lam = np.random.beta(mixup_alpha, mixup_alpha)
        x = x * lam + x2 * (1 - lam)

    y1 = torch.zeros((bs, num_classes), device=x.device).scatter_(1, y.view(-1,1), 1.0)
    y2oh = torch.zeros((bs, num_classes), device=x.device).scatter_(1, y2.view(-1,1), 1.0)
    ysoft = y1 * lam + y2oh * (1 - lam)
    return x, y, ysoft

class EMA:
    def __init__(self, model, decay=0.999):
        self.decay = decay
        self.shadow = {n: p.data.clone() for n,p in model.named_parameters() if p.requires_grad}
        self.backup = {}

    @torch.no_grad()
    def update(self, model):
        for n,p in model.named_parameters():
            if p.requires_grad:
                self.shadow[n] = self.shadow[n]*self.decay + p.data*(1-self.decay)

    def apply(self, model):
        self.backup = {}
        for n,p in model.named_parameters():
            if p.requires_grad:
                self.backup[n] = p.data.clone()
                p.data = self.shadow[n].clone()

    def restore(self, model):
        for n,p in model.named_parameters():
            if p.requires_grad:
                p.data = self.backup[n].clone()
        self.backup = {}

def batch_acc(logits, y):
    return (logits.argmax(1) == y).float().mean().item()

criterion_train = SoftTargetCrossEntropy(label_smoothing=0.1)
criterion_eval  = nn.CrossEntropyLoss()

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=0.05)

steps_per_epoch = len(train_loader)
total_steps = EPOCHS * steps_per_epoch
warmup_steps = int(0.05 * total_steps)

def lr_lambda(step):
    if step < warmup_steps:
        return step / max(1, warmup_steps)
    prog = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return 0.5 * (1 + math.cos(math.pi * prog))

scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
scaler = torch.amp.GradScaler("cuda", enabled=(device.type == "cuda"))

# ema = EMA(model, decay=0.999)

os.makedirs(OUT_DIR, exist_ok=True)
best_val = 0.0
best_path = f"{OUT_DIR}/best.pt"

global_step = 0
for epoch in range(1, EPOCHS+1):
    t0 = time.time()
    model.train()

    tr_loss = 0.0
    tr_acc = 0.0
    n = 0

    for x, y in train_loader:
        x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
        x, y_hard, y_soft = mixup_cutmix(x, y, num_classes=100, mixup_alpha=0.2, cutmix_alpha=1.0, p=0.8)

        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast("cuda", enabled=(device.type=="cuda")):
            logits = model(x)
            loss = criterion_train(logits, y_soft if y_soft is not None else y_hard)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # ema.update(model)

        tr_loss += loss.item() * x.size(0)
        tr_acc  += batch_acc(logits.detach(), y_hard) * x.size(0)
        n += x.size(0)

        scheduler.step()
        global_step += 1

    tr_loss /= n
    tr_acc  /= n

    # ---- eval (NO EMA) ----
    model.eval()
    correct = total = 0
    val_loss = 0.0
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
            logits = model(x)
            val_loss += criterion_eval(logits, y).item() * x.size(0)
            correct += (logits.argmax(1) == y).sum().item()
            total += y.size(0)
    val_loss /= total
    val_acc = correct / total

    dt = time.time() - t0
    print(f"Epoch {epoch:03d}/{EPOCHS} | train acc {tr_acc:.4f} loss {tr_loss:.4f} | val acc {val_acc:.4f} loss {val_loss:.4f} | {dt:.1f}s")

    if val_acc > best_val:
        best_val = val_acc
        torch.save({"model": model.state_dict()}, best_path)
        print("  [best] saved:", best_path)

"""### 產生 submission.csv（含 TTA）"""

ckpt = torch.load(f"{OUT_DIR}/best.pt", map_location="cpu")
model.load_state_dict(ckpt["model"])
model.to(device)

# ---- EMA OFF ----
# ema = EMA(model, decay=0.999)
# ema.shadow = ckpt["ema"]
# ema.apply(model)

model.eval()
ids, preds = [], []

with torch.no_grad():
    for x, names in test_loader:
        x = x.to(device, non_blocking=True)
        logits = model(x)
        if TTA:
            logits2 = model(torch.flip(x, dims=[3]))
            logits = (logits + logits2) / 2.0
        p = logits.argmax(1).cpu().tolist()
        ids += list(names)
        preds += p

# ---- EMA OFF ----
# ema.restore(model)

os.makedirs(OUT_DIR, exist_ok=True)
sub_path = f"{OUT_DIR}/submission.csv"
with open(sub_path, "w") as f:
    f.write("Id,Category\n")
    for i, p in zip(ids, preds):
        f.write(f"{i},{p}\n")

print("✅ Saved:", sub_path)
!ls -lah {OUT_DIR}

"""### 儲存模型


"""

from google.colab import drive
drive.mount('/content/drive')

save_path = '/content/drive/MyDrive/colab_model/Tiny_ImageNet/best_model.pth'
torch.save(model.state_dict(), save_path)

print(f"Model saved to {save_path}")

"""### 載入模型（這大概不是正確的位置）"""

model = YourModelClass()

# 載入模型權重
load_path = '/content/drive/MyDrive/colab_model/Tiny_ImageNet/best_model.pth'
model.load_state_dict(torch.load(load_path))

# 將模型移至設備（例如 GPU 或 CPU）
model.to(device)

print(f"Model loaded from {load_path}")